# perf script event handlers, generated by perf script -g python
# Licensed under the terms of the GNU GPL License version 2

# The common_* event handler fields are the most useful fields common to
# all events.  They don't necessarily correspond to the 'common_*' fields
# in the format files.  Those fields not available as handler params can
# be retrieved using Python functions of the form common_*(context).
# See the perf-script-python Documentation for the list of available functions.

from __future__ import print_function

import os
import sys
import json

sys.path.append(os.environ['PERF_EXEC_PATH'] + \
        '/scripts/python/Perf-Trace-Util/lib/Perf/Trace')

# from perf_trace_context import perf_sample_srcline, perf_script_context
import perf_trace_context as perf
from Core import *

dirs = {}

def trace_begin():
    print("in trace_begin")

def trace_end():
    print(f"Summary:")
    for dir, count in sorted(dirs.items(), key=lambda t: -t[1]):
        print(f"{dir}: {count}")

def process_event(event):
    file, _line = perf.perf_sample_srcline(perf.perf_script_context)
    if file is not None:
        dirs[os.path.dirname(file)] = dirs.get(os.path.dirname(file), 0) + 1

def trace_unhandled(event_name, context, event_fields_dict, perf_sample_dict):
    print("unhandled tracepoint")
